#!/bin/bash

# source
#https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/#:~:text=sudo%20dnf%20install%20fedora%2Dworkstation%2Drepositories  

# fedora is friendly with chrome apparently.
sudo dnf install fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install google-chrome-stable
